#!/usr/bin/env bash
# -*- coding: utf-8; mode: shell-script -*-

## Basic functions
function add_path() {
    while [[ $# -gt 0 ]]; do
        if [[ ":${PATH}:" != *:"$1":* ]]; then
            export PATH="${1}:${PATH}"
        fi
        shift
    done
}

## Enviroment variables
export LANG=en_US.UTF-8
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
if [[ -n "$SSH_CONNECTION" ]] || [[ -n "$SSH_CLIENT" ]] || [[ -n "$SSH_TTY" ]]; then
    export SSH_SERVER=1
fi

[[ -n "$LOGIN_SHELL" ]] && _LOGIN_SHELL="$LOGIN_SHELL"
[[ -n "$PREFIX_SYSTEM" ]] && _PREFIX_SYSTEM="$PREFIX_SYSTEM"
[[ -f $HOME/.envvars ]] && source $HOME/.envvars
export LOGIN_SHELL=${_LOGIN_SHELL:-${LOGIN_SHELL:-fish}}
export PREFIX_SYSTEM=${_PREFIX_SYSTEM:-${PREFIX_SYSTEM:-gentoo}}

## System Configurations
### Basic directory
mkdir -p \
      $HOME/.local/bin \
      $HOME/.local/src \
      $HOME/.local/share
### ssh-agent
function start-ssh-agent() {
    if [[ -f $HOME/.ssh-agent ]]; then
        source $HOME/.ssh-agent >/dev/null
    fi
    if [[ -z $SSH_AGENT_PID ]] || ! kill -0 $SSH_AGENT_PID >/dev/null 2>&1; then
        ssh-agent > $HOME/.ssh-agent
        source $HOME/.ssh-agent >/dev/null
    fi
    ssh-add "$HOME/.ssh/conf.d/vcs/id_rsa" >/dev/null 2>&1
}
if [[ -z $SSH_SERVER ]] && ! ssh-add -l >& /dev/null; then
    start-ssh-agent
fi

## Programming Languages
### Go
export GOPATH=$HOME/.go
add_path $GOPATH/bin
### Rust
export CARGO_HOME=$HOME/.cargo
add_path $CARGO_HOME/bin
if ! [[ -d $CARGO_HOME ]]; then
    read -p "==> Do you install Rust? [y/N] " install_rust
    if [[ "$install_rust" = "y" ]]; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
    fi
fi
### Ruby
# if command -v ruby >/dev/null; then
#     add_path $(ruby -e 'puts Gem.user_dir')/bin
# fi
### Python
export PYENV_ROOT=$HOME/.pyenv
add_path \
    $PYENV_ROOT/bin \
    $PYENV_ROOT/shims \
    $HOME/.poetry/bin

## My Configurations
### PATH
add_path \
    $HOME/bin \
    $HOME/.local/bin \
    $HOME/local/bin
### Prompt: Starship
# if ! command -v starship >/dev/null; then
#     curl -fsSL https://starship.rs/install.sh | env BIN_DIR=$HOME/.local/bin sh
# fi

## CLI tools
### ghq
export GHQ_ROOT=$HOME/src
export GHQ_SELECTOR=fzf
### fzf
export FZF_DEFAULT_OPTS="--height 30% --layout reverse --border --color 16"
export FZF_LEGACY_KEYBINDINGS=0
export FILTER="fzf $FZF_DEFAULT_OPTS"
### skim
export SKIM_DEFAULT_OPTIONS="--height 30% --layout reverse-list"
### trash-cli
export TRASH_DISABLED=${TRASH_DISABLED:-0}

## Set the signature
export LOADED_PROFILE=${BASH_SOURCE:-$0}
